"""autogenerate

Revision ID: 89d4fbeb420f
Revises: 261bac893099
Create Date: 2022-09-22 10:07:16.402958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89d4fbeb420f'
down_revision = '261bac893099'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(' leave_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('has_common', sa.BOOLEAN(), nullable=True),
    sa.Column('has_indefinite', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ leave_type_id'), ' leave_type', ['id'], unique=False)
    op.create_index(op.f('ix_ leave_type_name'), ' leave_type', ['name'], unique=False)
    op.drop_index('ix_leavetype_id', table_name='leave_type')
    op.drop_index('ix_leavetype_name', table_name='leave_type')
    op.drop_table('leave_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('has_common', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('has_indefinite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_leavetype_name', 'leave_type', ['name'], unique=False)
    op.create_index('ix_leavetype_id', 'leave_type', ['id'], unique=False)
    op.drop_index(op.f('ix_ leave_type_name'), table_name=' leave_type')
    op.drop_index(op.f('ix_ leave_type_id'), table_name=' leave_type')
    op.drop_table(' leave_type')
    # ### end Alembic commands ###
